services:
  mongodb:
    image: mongo:latest
    container_name: mongo_db_single_rs
    ports:
      - "27017:27017"
    volumes:
      - ./database/mongo:/data/db
    command: [ "--replSet", "rs0", "--port", "27017", "--bind_ip_all" ]
    restart: unless-stopped
    networks:
      - app-network


  auth-server:
    build:
      context: .
      dockerfile: apps/auth-server/Dockerfile
    container_name: auth-server-container
    env_file:
      - ./env/.env.production
    ports:
      - "5001:5001"
    depends_on:
      - mongodb
    restart: on-failure
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  mongo: