services:
  mongodb_dev:
    image: mongo:latest
    container_name: mongo_db_single_rs_dev
    ports:
      - "27017:27017"
    volumes:
      - ./database/mongo:/data/dev/db
    command: [ "--replSet", "rs0", "--port", "27017", "--bind_ip_all" ]
    restart: unless-stopped
