services:
  mongodb:
    image: mongo:latest
    container_name: mongo_db_single_rs
    ports:
      - "27017:27017"
    volumes:
      - ./database/mongo:/data/db # 데이터 볼륨 경로
    command: [ "--replSet", "rs0", "--port", "27017", "--bind_ip_all" ]
    restart: unless-stopped

volumes:
  mongo: