services:
  gateway-server:
    container_name: gateway-server-container
    build:
      context: ../../
      dockerfile: ./apps/gateway-server/Dockerfile
      no_cache: true
    tty: true
    stdin_open: true
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=production
    env_file:
      - ../.././env/.env.production
    restart: on-failure
    networks:
      - app-network

networks:
  app-network:
    external: true
