services:
  event-server:
    container_name: event-server-container
    build:
      context: ../../
      dockerfile: ./apps/event-server/Dockerfile
      no_cache: true
    tty: true
    stdin_open: true
    ports:
      - "5003:5003"
    environment:
      - NODE_ENV=production
    env_file:
      - ../.././env/.env.production
    restart: on-failure
    networks:
      - app-network

networks:
  app-network:
    external: true
